name: Movie_Sentiment_Analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - seaborn=0.13.2
  - matplotlib=3.10.0
  - ipython
  - scikit-learn
  - keras
  - nltk
  - spacy
  - regex
  - kagglehub
  - pip
  - pip:
      - tensorflow==2.16.1
      - keras==3.7.0
      - pyenchant
      - vaderSentiment
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl
