name: Movie_Sentiment_Analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - stopwords
      - vaderSentiment
      - nltk
      - tensorflow==2.16.1
      - keras
      - numpy
      - seaborn
      - scikit-learn
      - matplotlib
      - pyenchant
      - kagglehub
      - keras-tuner
  - spacy
  - pip:
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.5.0/en_core_web_lg-3.5.0.tar.gz
